"""
=========================================================
OmniMind AI Assistant
Agent Orchestrator
=========================================================

Coordinates all agents and executes plans generated by
the PlannerAgent.
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Dict

from agents.base_agent import AgentRequest, AgentResponse
from agents.planner_agent import (
    AgentType,
    ExecutionPlan,
    PlanStep,
)


class Orchestrator:
    """
    Executes execution plans by delegating work
    to specialized agents.
    """

    def __init__(
        self,
        planner,
        chat_agent,
        document_agent,
        vision_agent,
        web_agent,
        coding_agent,
        research_agent,
        memory_agent,
    ):

        self.planner = planner

        self.agents: Dict[AgentType, object] = {
            AgentType.CHAT: chat_agent,
            AgentType.DOCUMENT: document_agent,
            AgentType.VISION: vision_agent,
            AgentType.WEB: web_agent,
            AgentType.CODING: coding_agent,
            AgentType.RESEARCH: research_agent,
            AgentType.MEMORY: memory_agent,
        }

    # =====================================================
    # EXECUTE ONE STEP
    # =====================================================

    def execute_step(
        self,
        step: PlanStep,
        request: AgentRequest,
    ) -> AgentResponse:

        agent = self.agents.get(step.agent)

        if agent is None:
            raise ValueError(f"No agent registered for {step.agent}")

        merged_context = {}

        if request.context:
            merged_context.update(request.context)

        if step.parameters:
            merged_context.update(step.parameters)

        new_request = AgentRequest(
            query=request.query,
            context=merged_context,
            metadata=request.metadata,
        )

        return agent.run(new_request)

    # =====================================================
    # SEQUENTIAL EXECUTION
    # =====================================================

    def execute_sequential(
        self,
        plan: ExecutionPlan,
        request: AgentRequest,
    ) -> list[AgentResponse]:

        responses = []

        for step in plan.steps:

            responses.append(
                self.execute_step(
                    step,
                    request,
                )
            )

        return responses

    # =====================================================
    # PARALLEL EXECUTION
    # =====================================================

    def execute_parallel(
        self,
        plan: ExecutionPlan,
        request: AgentRequest,
    ) -> list[AgentResponse]:

        responses = []

        with ThreadPoolExecutor() as executor:

            futures = {
                executor.submit(
                    self.execute_step,
                    step,
                    request,
                ): step
                for step in plan.steps
            }

            for future in as_completed(futures):

                responses.append(future.result())

        return responses

    # =====================================================
    # COMBINE RESULTS
    # =====================================================

    def combine(
        self,
        responses: list[AgentResponse],
    ) -> AgentResponse:

        successful = [r for r in responses if r.success]

        failed = [r for r in responses if not r.success]

        output = "\n\n".join(str(r.output) for r in successful if r.output)

        metadata = {
            "completed_agents": [r.agent for r in successful],
            "failed_agents": [r.agent for r in failed],
            "steps": len(responses),
        }

        return AgentResponse(
            success=len(successful) > 0,
            output=output,
            agent="Orchestrator",
            metadata=metadata,
            error=None if len(failed) == 0 else "One or more agents failed.",
        )

    # =====================================================
    # MAIN ENTRY
    # =====================================================

    def run(
        self,
        request: AgentRequest,
    ) -> AgentResponse:

        planner_response = self.planner.run(request)

        if not planner_response.success:
            return planner_response

        plan: ExecutionPlan = planner_response.output

        if plan.parallel:

            responses = self.execute_parallel(
                plan,
                request,
            )

        else:

            responses = self.execute_sequential(
                plan,
                request,
            )

        return self.combine(responses)
